# coding: utf-8

"""
    Verbatim AI API

    **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____

    The version of the OpenAPI document: v1
    Contact: api@verbatim.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verbatim_client.api.authenticate_api import AuthenticateApi


class TestAuthenticateApi(unittest.TestCase):
    """AuthenticateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticateApi()

    def tearDown(self) -> None:
        pass

    def test_whoami(self) -> None:
        """Test case for whoami

        Info about the token used for authenticated this query
        """
        pass


if __name__ == '__main__':
    unittest.main()
