# coding: utf-8

"""
    Verbatim AI API

    **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____

    The version of the OpenAPI document: v1
    Contact: api@verbatim.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verbatim_client.api.corpus_api import CorpusApi


class TestCorpusApi(unittest.TestCase):
    """CorpusApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CorpusApi()

    def tearDown(self) -> None:
        pass

    def test_add1(self) -> None:
        """Test case for add1

        Create a new corpus
        """
        pass

    def test_delete1(self) -> None:
        """Test case for delete1

        Delete a Corpus
        """
        pass

    def test_get1(self) -> None:
        """Test case for get1

        Get a Corpus
        """
        pass

    def test_list2(self) -> None:
        """Test case for list2

        List corpus
        """
        pass

    def test_update1(self) -> None:
        """Test case for update1

        Update metadata of a Corpus
        """
        pass


if __name__ == '__main__':
    unittest.main()
