# coding: utf-8

"""
    Verbatim AI API

    **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____

    The version of the OpenAPI document: v1
    Contact: api@verbatim.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verbatim_client.api.document_api import DocumentApi


class TestDocumentApi(unittest.TestCase):
    """DocumentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentApi()

    def tearDown(self) -> None:
        pass

    def test_delete2(self) -> None:
        """Test case for delete2

        Delete a document
        """
        pass

    def test_download(self) -> None:
        """Test case for download

        Get the download link
        """
        pass

    def test_get_doc(self) -> None:
        """Test case for get_doc

        Get a document
        """
        pass

    def test_get_web_page(self) -> None:
        """Test case for get_web_page

        Get a WebPage
        """
        pass

    def test_list(self) -> None:
        """Test case for list

        List documents
        """
        pass

    def test_preview_doc(self) -> None:
        """Test case for preview_doc

        Preview a document image
        """
        pass

    def test_preview_web(self) -> None:
        """Test case for preview_web

        Preview a web page
        """
        pass

    def test_upload(self) -> None:
        """Test case for upload

        Upload a document
        """
        pass


if __name__ == '__main__':
    unittest.main()
