# coding: utf-8

"""
    Verbatim AI API

    **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____

    The version of the OpenAPI document: v1
    Contact: api@verbatim.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from verbatim_client.api.crawler_api import CrawlerApi


class TestCrawlerApi(unittest.TestCase):
    """CrawlerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CrawlerApi()

    def tearDown(self) -> None:
        pass

    def test_add(self) -> None:
        """Test case for add

        Create a new crawler
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete a crawler
        """
        pass

    def test_get(self) -> None:
        """Test case for get

        Get a crawler
        """
        pass

    def test_list1(self) -> None:
        """Test case for list1

        List the crawler
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update metadata of a Crawler
        """
        pass


if __name__ == '__main__':
    unittest.main()
