# coding: utf-8

# flake8: noqa
"""
    Verbatim AI API

    **Welcome on Verbatim AI Platform!**  You'll find here advanced specs of our APIs. You can play with these APIs on our **[Swagger Playground](https://www.verbatim.cloud/api-docs/swagger)**. Feel free to check our **[Cookbook](https://www.verbatim.cloud/cookbook)** to get samples and how start easily.  _____

    The version of the OpenAPI document: v1
    Contact: api@verbatim.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from verbatim_client.models.corpus import Corpus
from verbatim_client.models.corpus_metadata import CorpusMetadata
from verbatim_client.models.crawler import Crawler
from verbatim_client.models.crawler_metadata import CrawlerMetadata
from verbatim_client.models.document import Document
from verbatim_client.models.document_page import DocumentPage
from verbatim_client.models.document_resumable import DocumentResumable
from verbatim_client.models.document_sign import DocumentSign
from verbatim_client.models.error import Error
from verbatim_client.models.page_corpus import PageCorpus
from verbatim_client.models.page_crawler import PageCrawler
from verbatim_client.models.page_document import PageDocument
from verbatim_client.models.prompt_document_attachment import PromptDocumentAttachment
from verbatim_client.models.prompt_part import PromptPart
from verbatim_client.models.prompt_response import PromptResponse
from verbatim_client.models.prompt_web_attachment import PromptWebAttachment
from verbatim_client.models.token_info import TokenInfo
from verbatim_client.models.web_page import WebPage
